fn main() {
    if std::env::var("DOCS_RS").is_ok() {
        return;
    }

    #[cfg(feature = "sys")]
    sys::build_ffi();
}

#[cfg(feature = "sys")]
mod sys {
    use std::{
        env, fs, os,
        path::{Path, PathBuf},
        process::Command,
    };

    use pathdiff::diff_paths;

    /// The library name, used for the static library archive and the headers.
    /// Should be chosen as to not conflict with other library/header names.
    const LIB_NAME: &str = "sp1-recursion-core-sys";

    /// The name of all include directories involved, used to find and output header files.
    const INCLUDE_DIRNAME: &str = "include";

    /// The name of the directory to recursively search for source files in.
    const CPP_SOURCE_DIRNAME: &str = "cpp";

    /// The name of the directory to recursively search for cuda (.cu) source files in.
    //const CUDA_SOURCE_DIRNAME: &str = "cuda"; 

    const GPU_FFI_SOURCE_DIRNAME: &str = "gpu_ffi";

    /// The warning placed in the cbindgen header.
    const AUTOGEN_WARNING: &str =
        "/* Automatically generated by `cbindgen`. Not intended for manual editing. */";

    pub fn build_ffi() {
        // The name of the header generated by `cbindgen`.
        let cbindgen_hpp = &format!("{LIB_NAME}-cbindgen.hpp");

        // The crate directory.
        let crate_dir = PathBuf::from(env::var("CARGO_MANIFEST_DIR").unwrap());

        // The output directory, where built artifacts should be placed.
        let out_dir = PathBuf::from(env::var("OUT_DIR").unwrap());

        // The target directory that the cargo invocation is using.
        // Headers are symlinked into `target/include` purely for IDE purposes.
        let target_dir = {
            let mut dir = out_dir.clone();
            loop {
                if dir.ends_with("target") {
                    break dir;
                }
                if !dir.pop() {
                    panic!("OUT_DIR does not have parent called \"target\": {:?}", out_dir);
                }
            }
        };

        // The directory to read headers from.
        let source_include_dir = crate_dir.join(INCLUDE_DIRNAME);

        // The directory to place headers into.
        let target_include_dir = out_dir.join(INCLUDE_DIRNAME);

        // The directory to place symlinks to headers into. Has the fixed path "target/include".
        let target_include_dir_fixed = target_dir.join(INCLUDE_DIRNAME);


        let headers = glob::glob(source_include_dir.join("**/*.hpp").to_str().unwrap())
            .unwrap()
            .collect::<Result<Vec<_>, _>>()
            .unwrap();

        // Glob for C++ source files in the `cpp` directory.
        let compilation_units_cpp = glob::glob(crate_dir.join(CPP_SOURCE_DIRNAME).join("**/*.cpp").to_str().unwrap())
            .unwrap()
            .collect::<Result<Vec<_>, _>>()
            .unwrap();

        // Glob for CUDA Host FFI source files in the `gpu_ffi` directory.
        let compilation_units_gpu_ffi = glob::glob(crate_dir.join(GPU_FFI_SOURCE_DIRNAME).join("**/*.cpp").to_str().unwrap())
            .unwrap()
            .map(|p| p.unwrap())
            .collect::<Vec<_>>();

        // Tell Cargo that if the given file changes, to rerun this build script.
        println!("cargo::rerun-if-changed={INCLUDE_DIRNAME}");
        println!("cargo::rerun-if-changed={CPP_SOURCE_DIRNAME}");
        //println!("cargo::rerun-if-changed={CUDA_SOURCE_DIRNAME}");
        println!("cargo::rerun-if-changed={GPU_FFI_SOURCE_DIRNAME}");
        println!("cargo::rerun-if-changed=src");
        println!("cargo::rerun-if-changed=Cargo.toml");

        // Cargo build script metadata, used by dependents' build scripts.
        // The root directory containing the library archive.
        println!("cargo::metadata=root={}", out_dir.to_str().unwrap());

        // The include path defining the library's API.
        println!("cargo::metadata=include={}", target_include_dir.to_str().unwrap());

        // Generate a header containing bindings to the crate.
        match cbindgen::Builder::new()
            .with_pragma_once(true)
            .with_autogen_warning(AUTOGEN_WARNING)
            .with_no_includes()
            .with_sys_include("cstdint")
            .with_sys_include("cstddef")
            .with_parse_deps(true)
            .with_parse_include(&[
                "sp1-stark",
                "sp1-primitives",
                "sp1-core-machine",
                "p3-baby-bear",
                "sp1-core-executor",
                "p3-monty-31",
            ])
            .with_parse_extra_bindings(&["sp1-stark", "sp1-primitives", "p3-baby-bear", "p3-monty-31"])
            .rename_item("BabyBear", "BabyBearP3")
            .exclude_item("fri_pcs_compute_quotient_for_height_gpu") //sp1-stark/src/gpu/ffi function
            .exclude_item("fold_even_odd_gpu")
            .exclude_item("fri_commit_on_gpu")
            .exclude_item("quotient_values_gpu")
            .exclude_item("fri_fold_on_gpu")
            .exclude_item("fri_injection_gpu")
            .exclude_item("compute_and_accumulate_quotient_gpu")
            .exclude_item("stark_test_mat_compress_gpu")
            .exclude_item("stark_test_inv_denoms_gpu")
            .exclude_item("stark_test_quotient_loop_gpu")
            .exclude_item("stark_test_quartic_mul")
            .include_item("BaseAluEvent")
            .include_item("BaseAluValueCols")
            .include_item("BaseAluAccessCols")
            .include_item("BaseAluInstr")
            .include_item("ExtAluEvent")
            .include_item("ExtAluValueCols")
            .include_item("ExtAluInstr")
            .include_item("ExtAluAccessCols")
            .include_item("BatchFRIEvent")
            .include_item("BatchFRICols")
            .include_item("BatchFRIInstrFFI")
            .include_item("BatchFRIInstrFlat")
            .include_item("InstrsFlatIdex")
            .include_item("ExpReverseBitsEventFlatFFI")
            .include_item("ExpReverseBitsFlatIdex")
            .include_item("BatchFRIPreprocessedCols")
            .include_item("ExpReverseBitsEventFFI")
            .include_item("ExpReverseBitsInstrFlatFFI")
            .include_item("ExpReverseBitsLenCols")
            .include_item("ExpReverseBitsInstrFFI")
            .include_item("ExpReverseBitsLenPreprocessedCols")
            .include_item("FriFoldEvent")
            .include_item("FriFoldCols")
            .include_item("FriFoldInstrFFI")
            .include_item("FriFoldInstrRowFFI")
            .include_item("FriFoldPreprocessedCols")
            .include_item("SelectEvent")
            .include_item("SelectCols")
            .include_item("CommitPublicValuesEvent")
            .include_item("PublicValuesCols")
            .include_item("CommitPublicValuesInstr")
            .include_item("PublicValuesPreprocessedCols")
            .include_item("SelectEvent")
            .include_item("SelectCols")
            .include_item("SelectInstrPtx")
            .include_item("SelectInstr")
            .include_item("SelectPreprocessedCols")
            .include_item("Poseidon2Event")
            .include_item("Poseidon2")
            .include_item("Poseidon2Instr")
            .include_item("Poseidon2PreprocessedColsSkinny")
            .include_item("Poseidon2PreprocessedColsWide")
            .with_namespace("sp1_recursion_core_sys")
            .with_crate(crate_dir)
            .generate()
        {
            Ok(bindings) => { 
                // Write the bindings to the target include directory.
                let header_path = target_include_dir.join(cbindgen_hpp);
                if bindings.write_to_file(&header_path) {
                    // Symlink the header to the fixed include directory.
                    rel_symlink_file(header_path, target_include_dir_fixed.join(cbindgen_hpp));
                    println!("****Success!  generate {cbindgen_hpp}");
                }
            }
            Err(cbindgen::Error::ParseSyntaxError { .. }) => { 
                                                                println!("****Fail!  generate {cbindgen_hpp}");
                                                                return;
                                                                } /* Ignore parse errors so */
            // rust-analyzer can run.
            Err(e) => panic!("{:?}", e),

        }

        // Copy additional headers (unchanged)
        for header in &headers {
            let relpath = diff_paths(header, &source_include_dir).unwrap();
            let dst = target_include_dir.join(&relpath);
            if let Some(parent) = dst.parent() { fs::create_dir_all(parent).unwrap(); }
            fs::copy(header, &dst).unwrap();
            rel_symlink_file(dst, target_include_dir_fixed.join(relpath));
        }
        let include_dir = env::var("DEP_SP1_CORE_MACHINE_SYS_INCLUDE").unwrap();

        // --- Compile and Link FFI Library ---
        let mut all_obj_files_to_link: Vec<PathBuf> = vec![];

        // Compile pure C++ files into separate object files
        let pure_cpp_compiler_path = cc::Build::new() // Create a temporary builder to get compiler info
            .cpp(true).std("c++17")
            .get_compiler().path().to_path_buf(); 

        let pure_cpp_compiler_args: Vec<String> = {
            let mut builder = cc::Build::new();
            builder.files(&compilation_units_cpp)
                   .include(target_include_dir.clone())
                   .include(include_dir.clone());
            builder.cpp(true).std("c++17");
            builder.cargo_metadata(false); // Prevent cc from outputting extra cargo directives
            builder.out_dir(&out_dir); // Set output directory for .o files
            // Get the args for the compiler
            let mut args = Vec::new();
            for arg in builder.get_compiler().args() {
                args.push(arg.to_string_lossy().to_string());
            }
            args.push("-c".to_string()); // Compile only
            args
        };

        for file in &compilation_units_cpp {
            let obj_name = out_dir.join(file.file_stem().unwrap()).with_extension("o");
            let output = Command::new(&pure_cpp_compiler_path)
                .args(&pure_cpp_compiler_args)
                .arg(file.to_str().unwrap())
                .arg("-o").arg(obj_name.to_str().unwrap())
                .output().expect("Failed to compile pure cpp file");
            if !output.status.success() { 
                eprintln!("Pure C++ compilation stdout for {}:\n{}", file.display(), String::from_utf8_lossy(&output.stdout));
                eprintln!("Pure C++ compilation stderr for {}:\n{}", file.display(), String::from_utf8_lossy(&output.stderr));
                panic!("Pure C++ compilation failed for {}: {}", file.display(), String::from_utf8_lossy(&output.stderr));
            }
            all_obj_files_to_link.push(obj_name); // <--- Add g++ compiled objects
        }
        
        // Compile CUDA Host FFI .cpp files (from gpu_ffi/ directory)
        if cfg!(feature = "recursion_cuda") {
            let arch = env::var("CUDA_ARCH").unwrap_or_else(|_| "sm_75".into());
            let cuda_common_args = &[
                "-c", // Compile only, do not link
                &format!("-arch={}", arch),
                "--expt-relaxed-constexpr",
                //"-rdc=true", // Enable relocatable device code for dynamic parallelism
                "-I", target_include_dir.to_str().unwrap(),
                "-I", &include_dir.to_string(),
            ];

            for cpp_file in &compilation_units_gpu_ffi {
                let obj_name = out_dir.join(cpp_file.file_stem().unwrap()).with_extension("o");
                let output = Command::new("nvcc")
                    .args(cuda_common_args)
                    .arg("--x") // Force nvcc to treat the file as .cu
                    .arg("cu")
                    .arg("-o")
                    .arg(obj_name.to_str().unwrap())
                    .arg(cpp_file.to_str().unwrap())
                    .output()
                    .expect("Failed to execute nvcc command for gpu_ffi cpp file");

                if !output.status.success() {
                    eprintln!("CUDA gpu_ffi cpp compilation stdout for {}:\n{}", cpp_file.display(), String::from_utf8_lossy(&output.stdout));
                    eprintln!("CUDA gpu_ffi cpp compilation stderr for {}:\n{}", cpp_file.display(), String::from_utf8_lossy(&output.stderr));
                    panic!("CUDA gpu_ffi cpp compilation failed for {}:\n{}", cpp_file.display(), String::from_utf8_lossy(&output.stderr));
                }
                all_obj_files_to_link.push(obj_name);
            }

             // --- Final Linking with NVCC (for CUDA-enabled build) ---
            let lib_path = out_dir.join(format!("lib{}.a", LIB_NAME));
            let mut nvcc_linker_command = Command::new("nvcc");
            nvcc_linker_command.arg("-lib") // Create static library .a (equivalent to ar)
                               .arg("-o").arg(lib_path.to_str().unwrap());
            nvcc_linker_command.args(all_obj_files_to_link.iter().map(|p| p.to_str().unwrap())); // Add all .o files

            let output = nvcc_linker_command.output().expect("Failed to execute nvcc linker command");
            if !output.status.success() {
                eprintln!("nvcc linker stdout:\n{}", String::from_utf8_lossy(&output.stdout));
                eprintln!("nvcc linker stderr:\n{}", String::from_utf8_lossy(&output.stderr));
                panic!("Failed to link static library with nvcc.");
            }

            // Tell Cargo to link the generated static library
            println!("cargo::rustc-link-search=native={}", out_dir.to_str().unwrap());
            println!("cargo::rustc-link-lib=static={}", LIB_NAME);
            
            println!("cargo::rustc-link-search=native=/usr/local/cuda/lib64");
            println!("cargo::rustc-link-search=native=/usr/local/cuda/lib"); 

            // Tell Cargo to link CUDA runtime libraries (nvcc handles this implicitly, but explicit is fine)
            println!("cargo::rustc-link-lib=dylib=cuda");
            println!("cargo::rustc-link-lib=dylib=cudart");
            println!("cargo::rustc-link-lib=dylib=cudadevrt");
        }  else {
            // --- Final Static Library Archiving with AR (for non-CUDA build) ---
            // In this branch, all_obj_files_to_link only contains objects from pure C++ files
            let lib_path = out_dir.join(format!("lib{}.a", LIB_NAME));
            let mut ar_command = Command::new("ar");
            ar_command.arg("crus").arg(lib_path.to_str().unwrap());
            ar_command.args(all_obj_files_to_link.iter().map(|p| p.to_str().unwrap())); // Add all .o files

            let output = ar_command.output().expect("Failed to execute ar command");
            if !output.status.success() {
                eprintln!("ar stdout:\n{}", String::from_utf8_lossy(&output.stdout));
                eprintln!("ar stderr:\n{}", String::from_utf8_lossy(&output.stderr));
                panic!("Failed to create static library with ar.");
            }
            
            // Tell Cargo to link the generated static library
            println!("cargo::rustc-link-search=native={}", out_dir.to_str().unwrap());
            println!("cargo::rustc-link-lib=static={}", LIB_NAME);
        }

    }

    /// Creates a relative symlink pointing to `original` at `link`.
    fn rel_symlink_file<P, Q>(original: P, link: Q)
    where
        P: AsRef<Path>,
        Q: AsRef<Path>,
    {
        use os::unix::fs::symlink;

        let target_dir = link.as_ref().parent().unwrap();
        fs::create_dir_all(target_dir).unwrap();
        let _ = fs::remove_file(&link);
        let relpath = diff_paths(original, target_dir).unwrap();
        symlink(relpath, link).unwrap();
    }
}
