[package]
name = "sp1-stark"
description = "SP1 is a performant, 100% open-source, contributor-friendly zkVM."
readme = "../../README.md"
version = { workspace = true }
edition = { workspace = true }
license = { workspace = true }
repository = { workspace = true }
keywords = { workspace = true }
categories = { workspace = true }
links = "sp1_stark_cuda"

[dependencies]
# sp1
sp1-derive = { workspace = true }
sp1-primitives = { workspace = true }
spin = "0.9.8"

# p3
p3-monty-31 = { workspace = true }
p3-air = { workspace = true }
p3-field = { workspace = true }
p3-matrix = { workspace = true }
p3-uni-stark = { workspace = true }
p3-util = { workspace = true }
p3-challenger = { workspace = true }
p3-commit = { workspace = true }
p3-maybe-rayon = { workspace = true, features = ["parallel"] }
p3-baby-bear = { workspace = true }
p3-dft = { workspace = true }
p3-fri = { workspace = true }
p3-merkle-tree = { workspace = true }
p3-symmetric = { workspace = true }
p3-poseidon2 = { workspace = true }
p3-interpolation = { workspace = true }

once_cell = "1.18.0"
parking_lot = "0.12"
crossbeam-channel = "0.5"

serde_json = "1.0" #debug
# misc
serde = { workspace = true, features = ["derive"] }
hashbrown = { version = "0.14.5", features = ["serde", "inline-more"] }
itertools = { workspace = true }
tracing = { workspace = true }
rayon-scan = "0.1.1"
rayon = "1.10.0"
arrayref = "0.3.8"
num-bigint = { version = "0.4.3", default-features = false }

strum = "0.26.3"
strum_macros = "0.26.4"
sysinfo = "0.30.13"
num-traits = "0.2.19"

[features]
recursion_cuda = []

[dev-dependencies]
sp1-zkvm = { path = "../zkvm/entrypoint" }
rand = "0.8.5" 
rand_xoshiro = "0.6.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
p3-field = { workspace = true }
p3-baby-bear = { workspace = true }
rayon = "1.8"

[build-dependencies]
p3-baby-bear = { workspace = true }
cc = "1.1"
pathdiff = "0.2.1"
glob = "0.3.1"

[lints]
workspace = true
